### ISSUE TITLE
[Bug] No service for type 'Microsoft.Maui.IApplication' has been registered.

### ISSUE THREAD

**Issue by tompi** [BurkusCat/Burkus.Mvvm.Maui#58]
**Describe the bug**
Created new Maui project from template.
Removed ios target and verified it was running on android device.
After installing BurkusMvvm and removing shell I get this on start:

```
System.InvalidOperationException: No service for type 'Microsoft.Maui.IApplication' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[IApplication](IServiceProvider provider)
   at Microsoft.Maui.MauiApplication.OnCreate() in D:\a\_work\1\s\src\Core\src\Platform\Android\MauiApplication.cs:line 46
   at Android.App.Application.n_OnCreate(IntPtr jnienv, IntPtr native__this) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Android.App.Application.cs:line 1087
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 26
```

**To Reproduce**
First commit of this repo works(without burkus), second throws on start:
https://github.com/tompi/BurkusRepro

**Environment:**
- Rider
- Mac M1

**Comment by BurkusCat** [comment]
Hey @tompi, thanks for checking out the library and making a repro!

I think you are just missing `.UseMauiApp<App>()` in your builder. I updated your method to be:

``` csharp
    public static MauiApp CreateMauiApp()
    {
        var builder = MauiApp.CreateBuilder()
            .UseMauiApp<App>()
            .UseBurkusMvvm(burkusMvvm =>
            {
                burkusMvvm.OnStart(async (navigationService, serviceProvider) =>
                {

                        // we are logged in to the app
                        await navigationService.Navigate("/MainPage");
                });
            })
            .RegisterViews()
            .ConfigureFonts(fonts =>
            {
                fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
            });

#if DEBUG
        builder.Logging.AddDebug();
#endif

        return builder.Build();
    }
```

And the sample worked okay after doing that 👍

![image](https://github.com/BurkusCat/Burkus.Mvvm.Maui/assets/7528322/04175b33-f1a1-49fc-a002-dd13732dcb84)

**Comment by tompi** [comment]
ok, that was embarrassing... Sorry.

I vow to never again send a bug report on a friday afternoon :)
